mysite/movies/urls.py
from django.urls import path

from . import views

app_name='movies'
urlpatterns = [
    path('', views.home, name='home'),
    path('movies/', views.list_movies, name='movies-list'),
    path('theaters/', views.list_theaters, name='theaters-list'),
    path('movies/<int:movie_id>/', views.movie_detail, name="movie-details"),
    path('theaters/<slug:th_id>/', views.theater_detail, name="theater-details"),
    path('movies/<str:movie_genre>/', views.list_movies, name='movies-by-genre'),
    path('movies/<str:movie_genre>/<str:movie_genre1>/', views.list_movies, name='movies-by-complicated-genre'),
    path('api/<slug:slug>/', views.api, name='api'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
]

mysite/movies/models.py
from django.db import models

class Theater(models.Model):
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    name = models.CharField(max_length=100, default = "A Theater!")
    th_id = models.CharField(max_length=10, unique=True)
    lat = models.DecimalField(max_digits=10,decimal_places=4, null=True)
    long = models.DecimalField(max_digits=10,decimal_places=4, null=True)
    city = models.CharField(max_length=30)

    def __str__(self):
        return self.name + ' (' + self.th_id + ')'

class Movie(models.Model):
    title = models.CharField(max_length=100)
    theaters = models.ManyToManyField(Theater)
    movie_id = models.IntegerField(unique=True)
    runtime = models.IntegerField()
    releaseDate = models.DateField()
    poster = models.CharField(max_length=300)
    rating = models.CharField(max_length=10, null=True)
    movie_genre = models.CharField(max_length=50, null=True)

    def __str__(self):
        return self.title + ' (' + str(self.movie_id) + ')'
    # RATINGS = (
    #     ('G', 'G: General Audiences'),
    #     ('PG', 'PG: Parental Guidance Suggested'),
    #     ('PG-13', 'PG-13: Parents Strongly Cautioned'),
    #     ('R', 'R: Restricted'),
    #     ('NC-17', 'NC-17: Adults Only'),
    # )
    # GENRES = (
    #     ('Comedy', 'Comedy'),
    #     ('Suspense', 'Suspense/Thriller'),
    #     ('Drama', 'Drama'),
    #     ('Action', 'Action/Adventure'),
    #     ('Sci-Fi', 'Sci-Fi/Fantasy'),
    #     ('Animated', 'Animated'),
    #     ('Romance', 'Romance'),
    #     ('Horror', 'Horror'),
    #     ('Family', 'Family'),
    # )

class Showtime(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    theater = models.ForeignKey(Theater, on_delete=models.CASCADE, default="")
    time = models.CharField(max_length = 8)
    tickets = models.CharField(max_length = 250)

    def __str__(self):
        return self.movie.title + ' / ' + self.theater.name + ' / ' + self.time

mysite/movies/views.py
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import JsonResponse
from django.forms.models import model_to_dict
from . import models


def home(request):
    return render(request, "movies/home.html", {
        'theaters': models.Theater.objects.all(),
        'movies': models.Movie.objects.all()
    })

def list_movies(request, movie_genre='', movie_genre1=''):
    objects = models.Movie.objects.all()
    if movie_genre == '':
        return render(request, "movies/list.html", {
            "list_type": "Movies",
            "objects": objects
        })
    elif movie_genre1 == '':
        return render(request, "movies/list.html", {
            "list_type": "Movies",
            "objects": objects.filter(movie_genre__iexact=movie_genre),
        })
    else:
        return render(request, "movies/list.html", {
            "list_type": "Movies",
            "objects": objects.filter(movie_genre__iexact=movie_genre+"/"+movie_genre1),
        })

def list_theaters(request):
    # filter_by = request.GET.get('filter')
    # filter_val = request.GET.get('val')
    # filter_breadcrumb_name = None
    # filter_breadcrumb_url = None

    objects = models.Theater.objects.all()

    # if filter_by and filter_val:
    #     if filter_by == 'city':
    #         objects = objects.filter(movie__city__iexact=filter_val)
    #         filter_breadcrumb_name = "City"
    #         #filter_breadcrumb_url = reverse("winners:countries-list")
    #     if filter_by == 'movie':
    #         for o in objects:
    #             if o.movie_set
    #         objects = objects.filter(movie__genre__iexact=filter_val)
    #         filter_breadcrumb_name = "Genres"
            #filter_breadcrumb_url = reverse("winners:categories-list")

    return render(request, "movies/list.html", {
        "list_type": "Theaters",
        "objects": objects,
        # "filter_by": filter_by,
        # "filter_val": filter_val,
        # "filter_breadcrumb_name": filter_breadcrumb_name,
        # "filter_breadcrumb_url": filter_breadcrumb_url,
    })

def movie_detail(request, movie_id):
    movie = get_object_or_404(models.Movie, movie_id=movie_id)
    theater_objects = movie.theaters.all()
    showtime_objects = models.Showtime.objects.filter(movie=movie.pk)

    theaters = []
    for t, theater in enumerate(theater_objects):
        theaters.append(theater)

    showtimes = []
    for s, showtime in enumerate(showtime_objects):
        showtimes.append(showtime)

    context = {
        'title' : movie.title,
        'poster' : "https://" + movie.poster,
        'theaters' : theaters,
        'showtimes' : showtimes,
        'rating' : movie.rating,
        'runtime' : movie.runtime,
    }
    return render(request, "movies/movie_detail.html", context)

def theater_detail(request, th_id):
      theater = get_object_or_404(models.Theater, th_id=th_id)
      movie_objects = theater.movie_set.all()
      # movies = []
      # for m, movie in enumerate(movie_objects):
      #     movies.append(movie)

      context = {
        'name' : theater.name,
        'address' : theater.address,
        'phone' : theater.phone,
        'movies' : movie_objects,
      }
      return render(request, "movies/theater_detail.html", context)

def api(request, slug):

    if slug == 'movies':
        data = models.Movie.objects.values()
        print("type is movies")
    elif slug == 'showtimes':
        data = models.Showtime.objects.values()
        print("type is showtimes")
    else:
        data = models.Theater.objects.values()
        print("type is other, showing theaters")

    f_data = {"Data": [w for w in data]}

    return JsonResponse(f_data)

# Create your views here.

mysite/movies/templates/movies/base.html
{% load static %}


<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Fundango</title>
    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static "movies/css/styles.css" %}">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- fonts -->
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amiri" rel="stylesheet">

  </head>
  <body>
    {% block body %}
        <div class="container">
            {% block header %}
                <div class="row">
                    <div class="col-12">
                        <a class="header" href="/movies/"><h1>Fundango!</h1></a>
                    </div>
                </div>
            {% endblock %}
            {% block breadcrumb_nav %}
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        {% block breadcrumbs %}
                        {% endblock %}
                    </ol>
                </nav>
            {% endblock %}
            {% block content %}{% endblock %}
        </div>
    {% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://d3js.org/d3.v5.min.js"></script>
    {% block script %}
      <script src="{% static "movies/js/home.js" %}"></script>
      <script src="{% static "movies/js/apiKeys.js" %}"></script>
    {% endblock %}

  </body>
</html>

mysite/movies/templates/movies/home.html
{% extends "movies/base.html" %}
{% load static %}

{% block breadcrumbs %}
    <li class="breadcrumb-item active">Home</li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">
                        Where can I go watch a movie?
                    </h5>
                    <p class="card-text">
                        <a href="{% url "movies:theaters-list" %}">{{ theaters.count }} Theaters</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">
                        What's showing right now?
                    </h5>
                    <p class="card-text">
                        <a href="{% url "movies:movies-list" %}">{{ movies.count }} Movies</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-md-6">
        <div id="map"></div>
      </div>

      <div class="col-md-6">
        <div class="row">
          <div id="fam-bar-holder"></div>
        </div>
        <div class="row">
          <div id="date-bar-holder"></div>
        </div>
      </div>
      </div>
    </div>
{% endblock %}

{% block script %}
  <!-- <script>
  function initMap() {
    var uluru = {lat: -25.363, lng: 131.044};
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 4,
      center: uluru
    });
    var marker = new google.maps.Marker({
      position: uluru,
      map: map
    });
  }
  </script> -->
  <script defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDQoCNMvFuEHWambNcr82R-oq3J3IEn8pU&callback=initMap">
  </script>
  <script src="{% static "movies/data/new_counts.json" %}"></script>
  <script src="{% static "movies/js/home.js" %}"></script>
  <script src="{% static "movies/js/map.js" %}"></script>
  <script src="{% static "movies/js/fam-bar.js" %}"></script>
  <script src="{% static "movies/js/date-bar.js" %}"></script>


    <!-- <script src="{% static "winners/js/home.js" %}"></script> -->
{% endblock %}

mysite/movies/templates/movies/list.html
{% extends "movies/base.html" %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url "movies:home" %}">Home</a></li>
    <li class="breadcrumb-item active">List of {{ list_type}}</li>
{% endblock %}

{% block content %}
    <!-- <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <p>{{ objects.count }} {{ list_type }}
                    </p>
                </div>
            </div>
        </div>
    </div> -->
    <div class="row">
      {% for o in objects %}
        {% if list_type == "Movies" %}
          <div class="col-md-4">
            <div class="row movie-tile">
              <div class="col-md-5">
              <a href="https://{{ o.poster }}">
                <img alt="movie poster" src="https://{{ o.poster }}" style="width: 100px;">
              </a>
            </div>
              <div class="col-md-7 tile-info">
                <a href="/movies/movies/{{ o.movie_id }}"><h4>{{ o.title }}</h4></a>
                <p>Rating: {{o.rating}}</p>
                <p>Genre: {{o.movie_genre}}</p>
              </div>
            </div>
          </div>
        {% else %}
        <div class="col-md-4">
          <div class="row theater-tile">
            <a href="/movies/theaters/{{ o.th_id }}" class="theater-name">
              {{ o }}
            </a>
            <a href="https://www.google.com/maps/search/{{o.address}}" target="_blank"><p>Address: {{o.address}}</p></a>
            <img class="locator" src="http://maps.google.com/mapfiles/ms/icons/blue-dot.png">
            <p>Phone: {{o.phone}}</p>
          </div>
        </div>
        {% endif %}
      {% endfor %}
        </div>
    </div>
{% endblock %}

mysite/movies/templates/movies/movie_detail.html
{% extends "movies/base.html" %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url "movies:home" %}">Home</a></li>
    <li class="breadcrumb-item active">Movie Details: {{title}}</li>
{% endblock %}

{% block content %}
<div class="row">
  <div id="detail-header" class="col-md-12">
    <h2> {{ title }} </h2>
  </div>
</div>
<div id="movie-info" class="row">
  <div class="col-md-3">
    <img id="poster" alt="movie poster" src={{ poster }}>
  </div>
  <div class="col-md-9">
    <div class="row">
      <ul>
          <li>Rating: {{ rating }}</li>
          <li>Runtime: {{ runtime }} minutes</li>
      </ul>
    </div>
    <div class="row">
    </div>
  </div>
</div>
<div class="row">
    {% for t in theaters %}
    <div class="col-md-4">
      <div class="row theater-tile">
        <div class="col-md-12">
          <a href="/movies/theaters/{{ t.th_id }}" class="theater-name">
            {{ t.name }}
          </a>
        </div>
        <div class="col-md-12"
        <p>
          {% for s in showtimes %}
            {%if s.theater.name == t.name%}
              {{s.time}}m
            {%endif%}
          {% endfor %}
        </p>
      </div>
        <a href="https://www.google.com/maps/search/{{t.address}}" target="_blank"><p>Address: {{t.address}}</p></a>
        <img class="locator" src="http://maps.google.com/mapfiles/ms/icons/blue-dot.png">
        <p>Phone: {{t.phone}}</p>
      </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

mysite/movies/templates/movies/theater_detail.html
{% extends "movies/base.html" %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url "movies:home" %}">Home</a></li>
    <li class="breadcrumb-item active">Theater Details: {{name}}</li>
{% endblock %}

{% block content %}
<div class="row">
  <div id="detail-header" class="col-md-12">
    <h2>{{ name }}</h2>
  </div>
  <div class="col-md-12">
    <p>Theater Details</p>
    <ul>
      <li>Address {{ address }}</li>
      <li>Phone {{ phone }}</li>
    </ul>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h5>Now showing at {{name}}:</h5>
    </div>
  </div>
  <div class="row">
    {% for o in movies %}
    <div class="col-md-4">
      <div class="row movie-tile">
        <div class="col-md-5">
        <a href="https://{{ o.poster }}">
          <img alt="movie poster" src="https://{{ o.poster }}" style="width: 100px;">
        </a>
      </div>
        <div class="col-md-7 tile-info">
          <a href="/movies/movies/{{ o.movie_id }}"><h4>{{ o.title }}</h4></a>
          <p>Rating: {{o.rating}}</p>
          <p>Genre: {{o.movie_genre}}</p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}